name: "Update unreleased section in CHANGELOG"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: dangoslen/changelog-enforcer@204e7d3ef26579f4cd0fd759c57032656fdf23c7 # v3.6.1
      with:
        skipLabels: 'Skip-Changelog,dependencies,tests'
        versionPattern: ^`(v\\d?\\.\\d?\\.\\d|Unreleased) <\\S+>`__
        changeLogPath: CHANGELOG.rst
